<p>Welcome admin!</p>
<a class="btn btn-default" href="<?php echo App::config('app_url') ?>admin/logout">Logout</a>
<table class="table">        
    <thead>
        <tr>
            <th>Ime i prezime</th>
            <th>Email</th>
            <th>Smjer</th>
            <th>Godina</th>
            <th>Motiv</th>
            <th>Predznanje</th>
            <th>Jezici</th>
            <th>Kod</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($array as $row) { ?>
        <tr>
            <td><?php echo $row['ime'] ?></td>
            <td><?php echo $row['email'] ?></td>
            <td><?php echo $row['smjer'] ?></td>
            <td><?php echo $row['godina'] ?>.</td>
            <td><?php echo $row['motiv'] ?></td>
            <td><?php echo $row['predznanje'] ?></td>
            <td>
                <?php   
                    if(isset($row['php']) && $row['php'] == 1){ echo 'PHP&nbsp';};
                    if(isset($row['java']) && $row['java'] == 1){ echo 'Java&nbsp';};
                    if(isset($row['python']) && $row['python'] == 1){ echo 'Python&nbsp';};
                    if(isset($row['c']) && $row['c'] == 1){ echo 'C++&nbsp';};
                    if(isset($row['drugi']) && $row['drugi'] == 1){ echo 'Drugi';}; 
                ?>
            </td>
            <td><?php echo $row['kod'] ?></td>
        </tr>
        
        
        <?php }?>
    </tbody>
</table>